=== lcarvalhodev10/Gestor-Facturas-XML/facturas/factura.dtd
<!ELEMENT factura (emisor, cliente, lineas, total)>
<!ATTLIST factura numero ID #REQUIRED fecha CDATA #REQUIRED>

<!ELEMENT emisor (nombre, nif, direccionPostal)>
<!ELEMENT cliente (nombre, nif, direccionPostal)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT direccionPostal (#PCDATA)>


<!ELEMENT lineas (linea+)>
<!ELEMENT linea (descripcion, cantidad, precioUnitario, subtotal)>
<!ATTLIST linea codigo ID #REQUIRED>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precioUnitario (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>

<!ELEMENT total (#PCDATA)>

=== lcarvalhodev10/Gestor-Facturas-XML/facturas/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">

<factura numero="f001" fecha="17/02/2026">
    <emisor>
        <nombre>Pepito Pérez</nombre>
        <nif>12345678A</nif>
        <direccionPostal>Calle de la gaviota muerta número 666, San Juan de los Diablos, 45679, Santander</direccionPostal>
    </emisor>
    <cliente>
        <nombre>Ariana Grande</nombre>
        <nif>54645678A</nif>
        <direccionPostal>Calle del Perro Rabioso, 666, San Juan de los Diablos, 45679, Santander</direccionPostal>
    </cliente>
    <lineas>
        <linea codigo="m23">
            <descripcion></descripcion>
            <cantidad></cantidad>
            <precioUnitario></precioUnitario>
            <subtotal></subtotal>
        </linea>
        <linea codigo="i21">
            <descripcion></descripcion>
            <cantidad></cantidad>
            <precioUnitario></precioUnitario>
            <subtotal></subtotal>
        </linea>
        
    </lineas>
    <total></total>
</factura>
